// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ourApp9.Data;

#nullable disable

namespace ourApp9.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230821101618_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ourApp9.Models.CompanyInfo", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CId");

                    b.ToTable("CompanyInfos");

                    b.HasData(
                        new
                        {
                            CId = 1,
                            CName = "Samsung"
                        },
                        new
                        {
                            CId = 2,
                            CName = "HP"
                        },
                        new
                        {
                            CId = 3,
                            CName = "Apple"
                        },
                        new
                        {
                            CId = 4,
                            CName = "Dell"
                        },
                        new
                        {
                            CId = 5,
                            CName = "Toshiba"
                        },
                        new
                        {
                            CId = 6,
                            CName = "Redmi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
