// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ourApp9.Data;

#nullable disable

namespace ourApp9.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ourApp9.Models.CompanyInfo", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CId");

                    b.ToTable("CompanyInfos");

                    b.HasData(
                        new
                        {
                            CId = 1,
                            CName = "Samsung"
                        },
                        new
                        {
                            CId = 2,
                            CName = "HP"
                        },
                        new
                        {
                            CId = 3,
                            CName = "Apple"
                        },
                        new
                        {
                            CId = 4,
                            CName = "Dell"
                        },
                        new
                        {
                            CId = 5,
                            CName = "Toshiba"
                        },
                        new
                        {
                            CId = 6,
                            CName = "Redmi"
                        });
                });

            modelBuilder.Entity("ourApp9.Models.ProductInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<int>("PMDate")
                        .HasColumnType("int");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CId");

                    b.ToTable("ProductInfos");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CId = 1,
                            PMDate = 0,
                            PName = "Samsung",
                            PPrice = 12000
                        });
                });

            modelBuilder.Entity("ourApp9.Models.ProductInfo", b =>
                {
                    b.HasOne("ourApp9.Models.CompanyInfo", "CompanyInfo")
                        .WithMany()
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
